server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Redirigir todas las rutas al index.html (SPA Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para el microservicio de citas
    location /api/citas {
        proxy_pass http://ms_agendar_citas:3000/citas;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
