services:
  db_citas:
    image: postgres:16-alpine
    container_name: db_citas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: citas_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata_citas:/var/lib/postgresql/data
    networks:
      - app-network

  ms_agendar_citas:
    build:
      context: ./backend/ms_agendar_citas
      dockerfile: Dockerfile
    container_name: ms_agendar_citas
    restart: always
    ports:
      - '3001:3000'
    environment:
      PORT: 3000
      DB_HOST: db_citas
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: citas_db
      DB_DATABASE: citas_db
    depends_on:
      - db_citas
    networks:
      - app-network

  ms_citas_medicas:
    build:
      context: ./backend/ms_citas_medicas
      dockerfile: Dockerfile
    container_name: ms_citas_medicas
    restart: always
    ports:
      - '3002:3000'
    environment:
      PORT: 3000
      DB_HOST: db_citas
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: citas_db
      DB_DATABASE: citas_db
    depends_on:
      - db_citas
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - '4200:80'
    depends_on:
      - ms_agendar_citas
      - ms_citas_medicas
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata_citas: